const defaultSetting: LX.AppSetting = {
  version: '2.0',
  'common.isAutoTheme': false,
  'common.langId': null,
  'common.apiSource': '',
  'common.sourceNameType': 'alias',
  'common.shareType': 'system',
  'common.isAgreePact': false,
  'common.autoHidePlayBar': true,
  'common.drawerLayoutPosition': 'left',
  'common.homePageScroll': true,
  'common.allowProgressBarSeek': true,
  'common.showBackBtn': false,
  'common.showExitBtn': true,
  'common.useSystemFileSelector': true,
  'common.alwaysKeepStatusbarHeight': true,
  'common.guideDone': false,
  'localMusic.folderPath': '',

  'player.startupAutoPlay': true,
  'player.startupPushPlayDetailScreen': false,
  'player.togglePlayMethod': 'listLoop',
  'player.playQuality': '128k',
  'player.isSavePlayTime': true,
  'player.volume': 1,
  'player.playbackRate': 1,
  'player.cacheSize': '1024',
  'player.timeoutExit': '',
  'player.timeoutExitPlayed': true,
  'player.isAutoCleanPlayedList': false,
  'player.isHandleAudioFocus': true,
  'player.isEnableAudioOffload': true,
  'player.isShowLyricTranslation': false,
  'player.isShowLyricRoma': false,
  'player.isShowNotificationImage': true,
  'player.isS2t': false,
  'player.isShowBluetoothLyric': false,
  'player.isShowBluetoothFullLyric': false,

  // 'playDetail.isZoomActiveLrc': false,
  // 'playDetail.isShowLyricProgressSetting': false,
  'playDetail.background.type': 'theme',
  'playDetail.background.solidColor': '#000000',
  'playDetail.background.followCover': false,
  'playDetail.background.blurRadius': 20,
  'playDetail.cover.style': 'circle',
  'playDetail.cover.effect.glow': true,
  'playDetail.cover.effect.particles': true,
  'playDetail.cover.effect.rotate': true,
  'playDetail.cover.effect.swipe': true,

  'playDetail.effect.starfield.enabled': true,
  'playDetail.effect.starfield.particleCount': 40,
  'playDetail.effect.starfield.particleSize': 2,
  'playDetail.effect.starfield.speed': 1,
  'playDetail.effect.starfield.pattern': 'random',

  'playDetail.effect.lyricStage.enabled': true,

  'playDetail.effect.cinematic.enabled': true,
  'playDetail.effect.cinematic.zoomIntensity': 0.92,
  'playDetail.effect.cinematic.crossfadeDuration': 500,

  'playDetail.effect.controlBtn.enabled': true,
  'playDetail.effect.echo.enabled': true,
  'playDetail.effect.wallpaper.enabled': false,
  'playDetail.effect.lyric3d.enabled': false,
  'playDetail.effect.slideshow.enabled': false,
  'playDetail.effect.lyricGlow.enabled': true,
  'playDetail.effect.cinemaShake.enabled': false,
  'playDetail.effect.wallpaper.color': '',
  'playDetail.vertical.style.lrcLineCount': 7,
  'playDetail.effect.echo.color': '',
  'playDetail.effect.whiteParticles.enabled': true,
  'playDetail.effect.blurMask.enabled': false,
  'playDetail.effect.echo.speed': 1,
  'playDetail.effect.echo.amplitude': 1,
  'playDetail.effect.spectrum.enabled': true,

  'playDetail.progress.shimmer': true,
  'playDetail.style.align': 'left',
  'playDetail.vertical.style.lrcFontSize': 210,
  'playDetail.horizontal.style.lrcFontSize': 220,
  'playDetail.isShowLyricProgressSetting': false,

  'desktopLyric.enable': false,
  'desktopLyric.isLock': false,
  'desktopLyric.width': 100,
  'desktopLyric.maxLineNum': 5,
  'desktopLyric.isSingleLine': false,
  'desktopLyric.showToggleAnima': true,
  'desktopLyric.position.x': 0,
  'desktopLyric.position.y': 0,
  'desktopLyric.textPosition.x': 'left',
  'desktopLyric.textPosition.y': 'top',
  'desktopLyric.style.fontSize': 180,
  'desktopLyric.style.opacity': 100,
  'desktopLyric.style.lyricUnplayColor': 'rgba(255, 255, 255, 1)',
  'desktopLyric.style.lyricPlayedColor': 'rgba(7, 197, 86, 1)',
  'desktopLyric.style.lyricShadowColor': 'rgba(0, 0, 0, 0.6)',
  'desktopLyric.style.lyricGradientColors': null,
  'desktopLyric.style.lyricGradientPositions': null,

  'search.isShowHotSearch': false,
  'search.isShowHistorySearch': false,

  'list.isClickPlayList': false,
  'list.isShowSource': true,
  'list.isShowAlbumName': false,
  'list.isShowInterval': true,
  'list.isSaveScrollLocation': true,
  'list.addMusicLocationType': 'top',

  'download.fileName': '歌名 - 歌手',
  'download.dir': '',
  'download.conflictAction': 'overwrite',
  'download.enabled': false,

  'sync.enable': false,

  // 'theme.id': 'blue_plus',
  'theme.id': 'green',
  'theme.lightId': 'green',
  'theme.darkId': 'black',
  'theme.hideBgDark': false,
  'theme.dynamicBg': false,
  'theme.fontShadow': false,
}


// 使用新年皮肤
if (new Date().getMonth() < 2) {
  defaultSetting['theme.id'] = 'happy_new_year'
  defaultSetting['desktopLyric.style.lyricPlayedColor'] = 'rgba(255, 18, 34, 1)'
}

export default defaultSetting
